substitutions:
  friendly_name: All in One Sensor # the friendly name of your device, can be anything.

esphome:
  name: all-in-one-sensor # the name of your device. It should not contain any special characters or whitespaces. the device can be found in the network by this name.
  friendly_name: ${friendly_name}
  name_add_mac_suffix: True

esp32:
  variant: ${variant}
  framework:
    type: esp-idf

## Remove this if you don't want to track bluetooth device presence.
esp32_ble_tracker:
  scan_parameters:
    active: True # Whether to send scan-request packets to devices to gather more info (like devicename)
    interval: 211ms # suggested 211ms # default 320ms
    window: 30ms # suggested 120ms # default 30ms

## Remove this if you don't need to expand your home assistants bluetooth range
bluetooth_proxy:
  active: true

## Enables logging, eats ram, only enable if necessary.
# logger:
#   level: DEBUG

web_server:
  port: 80
  local: true

## Enables the Home Assistant API
api:
  id: api_id
  encryption: # Uses key set by Home Assistant
  on_client_connected:
    - script.execute: control_leds
  on_client_disconnected:
    - script.execute: control_leds

## Enables to update the firmware over the air
ota:
  - platform: esphome

wifi:
  id: wifi_id
  output_power: ${wifi_output_power}
  on_connect:
    - lambda: id(improv_ble_in_progress) = false;
    - script.execute: control_leds
  on_disconnect:
    - script.execute: control_leds

globals:
  - id: improv_ble_in_progress
    type: bool
    restore_value: no
    initial_value: "false"

esp32_improv:
  authorizer: none
  on_start:
    - lambda: id(improv_ble_in_progress) = true;
    - script.execute: control_leds
  on_provisioned:
    - lambda: id(improv_ble_in_progress) = false;
    - script.execute: control_leds
  on_stop:
    - lambda: id(improv_ble_in_progress) = false;
    - script.execute: control_leds

## adds support to choose your wifi through the esp fallback hotspot
# captive_portal:

sensor:
  ## this will report the uptime of the device. If your device reboots unexpectedly you can see it in this value.
  - platform: uptime
    type: seconds
    name: ${label_uptime}
    update_interval: 60s
    icon: mdi:timer-outline

  ## this will report the free memory. If your device reboots unexpectedly it may be because there is not enough free memory. In my experience there must be at least 40-50kb available at all times for reliable operation.
  - platform: template
    name: ${label_free_mem}
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL);
    icon: "mdi:memory"
    entity_category: diagnostic
    state_class: measurement
    unit_of_measurement: "b"
    update_interval: 60s
    disabled_by_default: true

  ## this reports the wifi signal strength of your wifi access point. If you want to reduce or increase your wifi output power of your access point you can use this value for reference. This value does not reflect the output power of the esp device, but the output power of the wifi access point.
  - platform: wifi_signal # Reports the WiFi signal strength/RSSI in dB
    disabled_by_default: true
    name: ${label_wifi_signal}
    id: wifi_signal_db
    update_interval: 1s
    entity_category: "diagnostic"

binary_sensor:
  ## this reports whether the device is online.
  - platform: status
    icon: mdi:chip
    name: "${friendly_name} Status"

## These values are necessary to calibrate the sensor.
number:
  - platform: template
    name: "${label_temperature} ${label_offset}"
    id: temperature_offset
    optimistic: true
    min_value: -100
    max_value: 100
    step: 0.1
    restore_value: true
    initial_value: ${temperature_offset_initial_value}
    unit_of_measurement: °C
    icon: mdi:thermometer-plus
    entity_category: config
  - platform: template
    name: "${label_humidity} ${label_offset}"
    id: humidity_offset
    optimistic: true
    min_value: -100
    max_value: 100
    step: 0.1
    restore_value: true
    initial_value: ${humidity_offset_initial_value}
    unit_of_measurement: "%"
    icon: mdi:water-plus
    entity_category: config

button:
  ## This button can be used to restart the device
  - platform: restart
    name: ${label_restart}
    icon: mdi:restart
